pizzashop/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using pizzashop_repository.ViewModels;
using pizzashop_service.Implementation;
using pizzashop_service.Interface;

namespace pizzashop.Controllers;

public class DashboardController : Controller
{
    private readonly IUserService _useService;

    public DashboardController(IUserService userService)
    {
        _useService = userService;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Profile()
    {
        var token = Request.Cookies["AuthToken"];
        var email = _useService.ExtractEmailFromToken(token);

        if (string.IsNullOrEmpty(email))
        {
            return RedirectToAction("Login", "Login");
        }

        var model = _useService.GetUserProfile(email);

        if (model == null)
        {
            return NotFound("User Not Found");
        }

        ViewBag.Email = email;
        return View(model);
    }

    [HttpPost]
    public IActionResult Profile(UserTableViewModel model)
    {
        var token = Request.Cookies["AuthToken"];
        var email = _useService.ExtractEmailFromToken(token);

        if (string.IsNullOrEmpty(email))
        {
            return RedirectToAction("Login", "Login");
        }

        var success = _useService.UpdateUserProfile(email, model);

        var coockieopt = new CookieOptions
            {
                HttpOnly = true,
                Secure = true,
                SameSite = SameSiteMode.Strict
            };

        Response.Cookies.Append("Username", model.Username, coockieopt);
        Response.Cookies.Append("ProfileImgPath", string.IsNullOrEmpty(model.ProfileImagePath) ? "/images/Default_pfp.svg.png" : model.ProfileImagePath, coockieopt);


        if (!success)
        {
            return NotFound("User Not Found");
        }

        TempData["success"] = "Profile updated successfully.";
        return View(model);
    }

    [HttpGet]
    public IActionResult ChangePassword()
    {
        return View();
    }

    [HttpPost]
    public IActionResult ChangePassword(ChangePasswordViewModel model)
    {
        var token = Request.Cookies["AuthToken"];
        var userEmail = _useService.ExtractEmailFromToken(token);

        if (string.IsNullOrEmpty(userEmail))
        {
            return RedirectToAction("Login", "Login");
        }

        var result = _useService.ChangePassword(userEmail, model);

        if (result == "UserNotFound")
        {
            TempData["error"] = "User not found.";
            return View(model);
        }

        if (result == "IncorrectPassword")
        {
            TempData["error"] = "Current password is incorrect.";
            return View(model);
        }

        TempData["success"] = "Password updated successfully.";
        return RedirectToAction("Login", "Login"); ;
    }

    public IActionResult Logout()
    {
        if (Request.Cookies["UserEmail"] != null)
        {
            Response.Cookies.Delete("UserEmail");
            Response.Cookies.Delete("AuthToken");
            Response.Cookies.Delete("Username");
            Response.Cookies.Delete("ProfileImgPath");

        }
        return RedirectToAction("Login", "Auth");
    }

}

pizzashop/Controllers/OrdersController.cs
using System.Security.Cryptography.Pkcs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using pizzashop_service.Interface;

namespace pizzashop.Controllers;

public class OrdersController : Controller
{
    private readonly IOredersService _oredersService;

    public OrdersController(IOredersService oredersService)
    {
        _oredersService = oredersService;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> GetOrders(int pageNumber = 1, int pageSize = 5, string sortBy = "Id", string sortOrder = "asc", string searchTerm = "", string status = "All", string dateRange = "All time", string fromDate = "", string toDate = "")
    {
        var pagedItems = await _oredersService.GetOrdersAsync(pageNumber, pageSize, sortBy, sortOrder, searchTerm, status, dateRange, fromDate, toDate);
        return PartialView("_OrderTablePartial", pagedItems);
    }

    [HttpGet]
    public IActionResult ExportOrders(string status, string date, string searchText)
    {
        // Ensure valid parameters
        status = status ?? "";
        date = date ?? "";
        searchText = searchText ?? "";

        // Generate Excel file
        byte[] fileContent = _oredersService.GenerateExcel(status, date, searchText);

        if (fileContent == null || fileContent.Length == 0)
        {
            return BadRequest("Failed to generate Excel file.");
        }

        string fileName = $"Orders_{DateTime.Now:yyyyMMdd_HHmmss}.xlsx";
        return File(fileContent,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    fileName);
    }

    public async Task<IActionResult> OrderDetails(int id)
    {
        var orderDetails = await _oredersService.GetOrderDetailsAsync(id);
        if (orderDetails == null)
        {
            return NotFound();
        }
        return View(orderDetails);
    }
}

pizzashop/Controllers/TableAndSectionController.cs
using Microsoft.AspNetCore.Mvc;
using pizzashop_repository.ViewModels;
using pizzashop_service.Interface;

namespace pizzashop.Controllers;

public class TableAndSectionController : Controller
{
    private readonly ITableAndSectionService _tableAndSectionService;

    public TableAndSectionController(ITableAndSectionService tableAndSectionService)
    {
        _tableAndSectionService = tableAndSectionService;
    }

    public async Task<IActionResult> Index()
    {
        var sections = await _tableAndSectionService.GetSectionsAsync();

        sections = sections.OrderBy(c => c.Id).ToList();

        var viewmodel = new TableAndSectionViewModel
        {
            Sections = sections
        };
        return View(viewmodel);
    }

    [HttpGet]
    public async Task<IActionResult> GetSections()
    {
        var sections = await _tableAndSectionService.GetSectionsAsync();

        sections = sections.OrderBy(c => c.Id).ToList();
        return PartialView("_SectionsPartial", sections);
    }

    [HttpGet]
    public async Task<IActionResult> GetTableBySection(int SectionId = 1, int pageNumber = 1, int pageSize = 5, string searchTerm = "")
    {
        var tables = await _tableAndSectionService.GetTableBySectionAsync(SectionId, pageNumber, pageSize, searchTerm);
        return PartialView("_TableListPartial", tables);
    }

    [HttpPost]
    public async Task<IActionResult> AddSection([FromBody] SectionsViewModal model)
    {
        if (string.IsNullOrWhiteSpace(model.Name))
        {
            return Json(new { success = false, message = "Section name is required" });
        }
        var section = await _tableAndSectionService.AddSectionAsync(model.Name, model.Description);
        return Json(new { success = true, section });
    }

    [HttpGet]
    public async Task<IActionResult> GetSectionById(int id)
    {
        var model = await _tableAndSectionService.GetSectionById(id);
        if (model != null)
        {
            return Json(model);
        }
        return Json(null);
    }

    [HttpPut]
    public async Task<IActionResult> UpdateSection([FromBody] SectionsViewModal model)
    {
        if (model == null || model.Id == 0)
        {
            return BadRequest(new { success = false, message = "Invalid Section Data." });
        }

        bool result = await _tableAndSectionService.UpdateSectionAsync(model);

        if (result)
        {
            return Ok(new { success = true, message = "Section updated successfully." });
        }
        else
        {
            return BadRequest(new { success = false, message = "Failed to update category." });
        }
    }


    [HttpPost]
    public async Task<IActionResult> DeleteSections([FromBody] SectionsViewModal request)
    {
        bool result = await _tableAndSectionService.SoftDeleteSectionAsync(request.Id);
        return result ? Ok(new { success = true }) : BadRequest(new { success = false });
    }

    [HttpPost]
    public async Task<IActionResult> AddTable(TableViewModel model)
    {
        if (!ModelState.IsValid)
        {

            var errors = ModelState.SelectMany(x => x.Value.Errors)
                               .Select(x => x.ErrorMessage)
                               .ToList();
            foreach (var error in errors)
            {
                Console.WriteLine("Error: " + error);
            }
            return Json(new { success = false, message = "Invalid data provided." });
        }

        var existingTable = await _tableAndSectionService.GetTableByNameAsync(model.Name);
        if (existingTable != null)
        {
            return Json(new { success = false, message = "A table with this name already exists." });
        }

        var result = await _tableAndSectionService.AddTableAsync(model);

        if (result)
        {
            return Json(new { success = true, message = "Table added successfully." });
        }
        else
        {
            return Json(new { success = false, message = "Failed to add Table." });
        }
    }

    [HttpGet]
    public async Task<IActionResult> GetTableById(int id)
    {
        var table = await _tableAndSectionService.GetTableById(id);

        if (table == null)
        {
            return NotFound();
        }

        return Json(table);
    }

    [HttpPost]
    public async Task<IActionResult> EditTable([FromBody] TableViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return Json(new
            {
                success = false,
                message = "Invalid data provided.",
                errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage)
            });
        }

        var result = await _tableAndSectionService.UpdateTableAsync(model);

        if (!result)
        {
            return Json(new { success = false, message = "An error occurred while updating the table." });
        }

        return Json(new { success = true, message = "Table updated successfully!" });
    }

    [HttpPost]
    public async Task<IActionResult> DeleteTable([FromBody] TableViewModel request)
    {
        bool result = await _tableAndSectionService.SoftDeleteTableAsync(request.Id);
        return result ? Ok(new { success = true }) : Json(new { success = false });
    }


    public IActionResult SoftDeleteTables([FromBody] List<int> tableIds)
    {
        if (tableIds == null || tableIds.Count == 0)
        {
            return Json(new { success = false, message = "No item Selected" });
        }

        _tableAndSectionService.SoftDeleteTablesAsync(tableIds);
        return Json(new { success = true });
    }

}

pizzashop/Controllers/TaxesAndFeesController.cs
using Microsoft.AspNetCore.Mvc;
using pizzashop_repository.ViewModels;
using pizzashop_service.Interface;

namespace pizzashop.Controllers;

public class TaxesAndFeesController : Controller
{
    private readonly ITaxesAndFeesService _taxesAndFeesService;

    public TaxesAndFeesController(ITaxesAndFeesService taxesAndFeesService)
    {
        _taxesAndFeesService = taxesAndFeesService;
    }
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> GetTaxesAndFees(int pageNumber = 1, int pageSize = 5, string searchTerm = "")
    {
        var pagedItems = await _taxesAndFeesService.GetTaxesAndFeesAsync(pageNumber, pageSize, searchTerm);
        return PartialView("_TaxesAndFeesPartial", pagedItems);
    }

    [HttpPost]
    public async Task<IActionResult> AddTax(TaxsAndFeesViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return Json(new { success = false, message = "Invalid data provided." });
        }



        var result = await _taxesAndFeesService.AddTaxAsync(model);

        if (result)
        {
            return Json(new { success = true, message = "Tax added successfully." });
        }
        else
        {
            return Json(new { success = false, message = "Failed to add Tax." });
        }
    }

    [HttpGet]
    public async Task<IActionResult> GetTaxById(int id)
    {
        var tax = await _taxesAndFeesService.GetTaxByIdAsync(id);

        if (tax == null)
        {
            return NotFound();
        }

        return Json(tax);
    }

    [HttpPost]
    public async Task<IActionResult> DeleteTax([FromBody] ItemViewModel request)
    {
        bool result = await _taxesAndFeesService.SoftDeleteTaxAsync(request.Id);
        return result ? Ok(new { success = true }) : Json(new { success = false });
    }

    [HttpPost]
    public async Task<IActionResult> EditTax([FromBody] TaxsAndFeesViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return Json(new
            {
                success = false,
                message = "Invalid data provided.",
                errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage)
            });
        }

        // var existingTable = await _taxesAndFeesService.GetTableByNameAsync(model.Name);
        // if (existingTable != null)
        // {
        //     return Json(new { success = false, message = "A table with this name already exists." });
        // }

        var result = await _taxesAndFeesService.UpdateTaxAsync(model);

        if (!result)
        {
            return Json(new { success = false, message = "An error occurred while updating the table." });
        }

        return Json(new { success = true, message = "Tax updated successfully!" });
    }
}

pizzashop/Views/Shared/_Layout.cshtml
@{
    var username = Context.Request.Cookies["Username"];
    var profileimg = @Context.Request.Cookies["ProfileImgPath"];
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add New User</title>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/users.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />


</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-color ">
        <div class="container-fluid navbar-pf">

            <button class="btn btn-light d-lg-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#sidebar"
                aria-controls="sidebar">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list"
                    viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                        d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5" />
                </svg>
            </button>

            <div class="btn-group">
                <img class=" dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" width="35"
                    src="~/images/Default_pfp.svg.png" alt="">
                <ul class="dropdown-menu dropdown-menu-end ">
                    <li><a class="dropdown-item d-flex align-items-center" href="#">
                            <img class="me-2" width="25" src="@profileimg" alt="">
                            <p class="m-0">@username</p>
                        </a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item d-flex align-items-center" asp-action="Profile"
                            asp-controller="Dashboard">
                            <img class="me-2 dashboard-icon" src="@profileimg" alt="">
                            <p class="m-0">My profile</p>
                        </a></li>
                    <li><a class="dropdown-item d-flex align-items-center" asp-action="ChangePassword"
                            asp-controller="Dashboard">
                            <img class="dashboard-icon me-1" src="~/images/icons/arrow-clockwise.svg" alt="">
                            <p class="m-0">Change Password</p>
                        </a></li>
                    <li><a class="dropdown-item d-flex align-items-center" data-bs-toggle="modal"
                            data-bs-target="#exampleModal">
                            <div class="d-flex">
                                <img class="dashboard-icon me-1" src="~/images/icons/box-arrow-right.svg" alt="">
                                <p class="m-0">Logout</p>
                            </div>
                        </a></li>
                </ul>
            </div>
            <!-- Modal -->

            <div class="modal fade " id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" style="display: flex; justify-content: center;">
                    <form>
                        <div class="modal-content">
                            <div class="modal-body">
                                <div class="d-flex justify-content-center"><img class="warning-img"
                                        src="~/images/toppng.com-warning-icon-2400x2400.png" alt=""></div>
                                <div class="d-flex justify-content-center">Are you sure you want to logout?
                                </div>
                            </div>
                            <div class="modal-footer d-flex justify-content-center">
                                <div class=" mt-3">
                                    <button type="submit" asp-action="Logout" asp-controller="Dashboard"
                                        class="btn navbar-color text-white">Yes</button>
                                    <button type="submit" class="btn cancel-btn-color ms-1">No</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </nav>


    <div class="offcanvas offcanvas-start bg-light pizzasidebar d-lg-block show" tabindex="-1" id="sidebar"
        data-bs-scroll="true">
        <div class="offcanvas-header">
            <div class="d-flex justify-content-center">
                <img class="img-fluid w-50 shop-logo" src="~/images/logos/pizzashop_logo.png" alt="">
                <div class="ms-2 h6 text-center align-item-center shop-name" style="align-content: center;">
                    <strong>PIZZASHOP</strong>
                </div>
                <div><button type="button" class="btn-close d-lg-none" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button></div>
            </div>

        </div>
        <div class="offcanvas-body">
            <ul class="nav flex-column">
                <li class="nav-item mb-2 sidebarlist-hover"><a class="nav-link" asp-action="Index"
                        asp-controller="Dashboard">
                        <div class="d-flex">
                            <div>
                                <img class="dashboard-icon" src="~/images/icons/border-all.svg" alt="">
                            </div>

                            <div class="sidebar-name ms-2"><strong>Dashboard</strong></div>
                        </div>
                    </a></li>

                <li class="nav-item mb-2 sidebarlist-hover"><a class="nav-link active" asp-action="UsersList"
                        asp-controller="Users">
                        <div class="d-flex">
                            <div>
                                <img class="dashboard-icon" src="~/images/icons/people.svg" alt="">
                            </div>

                            <div class="sidebar-name ms-2"><strong>User</strong></div>
                        </div>
                    </a></li>

                <li class="nav-item mb-2 sidebarlist-hover"><a class="nav-link" asp-action="Roles"
                        asp-controller="Auth">
                        <div class="d-flex">
                            <div>
                                <img class="dashboard-icon" src="~/images/icons/person-gear.svg" alt="">
                            </div>

                            <div class="sidebar-name ms-2"><strong>Role and Permission</strong></div>
                        </div>
                    </a></li>
                <li class="nav-item mb-2 sidebarlist-hover"><a class="nav-link" asp-action="Menu" asp-controller="Menu">
                        <div class="d-flex">
                            <div>
                                <img class="dashboard-icon" src="~/images/icons/clipboard.svg" alt="">
                            </div>

                            <div class="sidebar-name ms-2"><strong>Menu</strong></div>
                        </div>
                    </a></li>
                <li class="nav-item mb-2 sidebarlist-hover"><a class="nav-link" asp-action="Index"
                        asp-controller="TableAndSection">
                        <div class="d-flex">
                            <div>
                                <img class="dashboard-icon" src="~/images/icons/square.svg" alt="">
                            </div>

                            <div class="sidebar-name ms-2"><strong>Table And Section</strong></div>
                        </div>
                    </a></li>
                <li class="nav-item mb-2 sidebarlist-hover"><a class="nav-link" asp-action="Index" asp-controller="TaxesAndFees">
                        <div class="d-flex">
                            <div>
                                <img class="dashboard-icon" src="~/images/icons/cash-coin.svg" alt="">
                            </div>

                            <div class="sidebar-name ms-2"><strong>Taxs And Fees</strong></div>
                        </div>
                    </a></li>
                <li class="nav-item mb-2 sidebarlist-hover"><a class="nav-link" asp-action="Index" asp-controller="Orders">
                        <div class="d-flex">
                            <div>
                                <img class="dashboard-icon" src="~/images/icons/clipboard-check.svg" alt="">
                            </div>
                            <div class="sidebar-name ms-2"><strong>Oreders</strong></div>
                        </div>
                    </a></li>
                <li class="nav-item mb-2 sidebarlist-hover"><a class="nav-link" href="#">
                        <div class="d-flex">
                            <div>
                                <img class="dashboard-icon" src="~/images/icons/person-rolodex.svg" alt="">
                            </div>

                            <div class="sidebar-name ms-2"><strong>Customers</strong></div>
                        </div>
                    </a></li>
            </ul>
        </div>
    </div>


    <div id="main-content">
        <partial name="_Notification.cshtml"></partial>
        @RenderBody()
    </div>

    <script>
        function handleResize() {
            let sidebar = document.getElementById("sidebar");
            let mainContent = document.getElementById("main-content");

            if (window.innerWidth >= 992) {

                sidebar.classList.add("show");
                sidebar.classList.add("d-lg-block");
                sidebar.style.transform = "none";
                sidebar.style.visibility = "visible";
                mainContent.style.marginLeft = "300px"; // Shift content
            } else {

                sidebar.classList.remove("show");
                sidebar.classList.remove("d-lg-block");
                sidebar.style.transform = "";
                sidebar.style.visibility = "";
                mainContent.style.marginLeft = "0";
            }
        }

        handleResize();
        window.addEventListener("resize", handleResize);
    </script>
    <script src="~/js/custom.js"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>

    <script src="~/js/bootstrap.bundle.min.js"></script>
</body>

</html>

pizzashop/Views/Shared/_Notification.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script type="text/javascript">
    // Set Toastr options globally
    toastr.options = {
        "closeButton": true, // Show close button
        "debug": false,
        "newestOnTop": true,
        "progressBar": true,
        "positionClass": "toast-top-right", // Position of toast
        "preventDuplicates": true,
        "showDuration": "300",
        "hideDuration": "1000",
        "timeOut": "5000", // Toast will disappear after 5 seconds
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    };

    // Display the toast message
    @if (TempData["error"] != null)
    {
        <text>
            toastr.error('@TempData["error"]');
        </text>
    }

    @if (TempData["success"] != null)
    {
        <text>
            toastr.success('@TempData["success"]');
        </text>
    }
</script>